### ISSUE TITLE
Update documentation for RHEL 8

### ISSUE THREAD

**Issue by sirio3mil** [MicrosoftDocs/sql-docs.es-es#74]
This are more accurate commands for RHEL 8 using dnf instead of yum

```
dnf -y install dnf-plugins-core
dnf config-manager --add-repo https://packages.microsoft.com/config/rhel/8/mssql-server-2019.repo
dnf config-manager --add-repo https://packages.microsoft.com/config/rhel/8/prod.repo
ACCEPT_EULA=Y dnf -y install mssql-server
```

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 3b543b57-f397-779d-6fe4-1bc2ecd3bdca
* Version Independent ID: e274a0f3-ec74-e809-f4d3-515782b29a92
* Content: [RHEL: Instalación de SQL Server en Linux - SQL Server](https://docs.microsoft.com/es-es/sql/linux/quickstart-install-connect-red-hat?view=sql-server-ver15#feedback)
* Content Source: [docs/linux/quickstart-install-connect-red-hat.md](https://github.com/MicrosoftDocs/sql-docs.es-es/blob/live/docs/linux/quickstart-install-connect-red-hat.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by srvbpigh** [comment]
Hello, @sirio3mil
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @sirio3mil, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/sql-docs/issues/4134. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
